"use client";

import Head from "next/head";
import "./globals.css"
import { AiFillLinkedin, AiFillYoutube, AiFillGithub, AiOutlineBook, AiOutlineLink } from "react-icons/ai";
import {FaCloudMoonRain} from "react-icons/fa";
import UseAnimations from "react-useanimations";
import arrowDown from 'react-useanimations/lib/arrowDown';
import Image from "next/image";
import deved from "../public/prog.png";
import design from "../public/complements.gif";
import code from "../public/codecard.gif";
import couch from "../public/couch.gif";
import ecommerce from "../public/screenshotEcommerce.png";
import CECQ from "../public/screenshotCECQ.png";
import tenis from "../public/screenshotTenis.png";
import clinica from "../public/screenshotClinica.png";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const imageLoader = ({ src, width, quality }) => {
    return `https://example.com/${src}?w=${width}&q=${quality || 75}`;
  };
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Tomas Martin Portfolio</title>
        <meta name="description" content="Generated by me"></meta>
        <link rel="icon" href="./favicon.ico"></link>
      </Head>

      <main className="bg-sky-50 px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen ">
          <nav className="py-5 mb-12  flex justify-between">
            <ul className="text-cyan-900 flex items-center  md:text-xl dark:text-red-400">
              <li className=" flex cursor-pointer">
                <FaCloudMoonRain 
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pinter text-3xl"
                />
              </li>
              <li>
                <Link
                  href="/TomasMartinCV.pdf"
                  className=" flex cursor-pointer text-3xl py-2 ml-8"
                >
                <AiOutlineBook/>
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-cyan-900 font-medium md:text-6xl dark:text-red-400">
              Tomas Martin
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              University Systems Analyst
            </h3>
            <p className="text-md pt-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
              <span className="text-cyan-600 font-bold dark:text-red-400	">+1</span> years of experience in the IT field.
            </p>
          </div>
          <div className=" text-4xl flex justify-center gap-12 text-gray-600 dark:text-white ">
            <a
            
            href="https://www.linkedin.com/in/tomas-martin-02816125b/">
              <AiFillLinkedin />
            </a>
            <a href="https://www.youtube.com/@tomasmartin9093">
              <AiFillYoutube />
            </a>
            <a href="https://github.com/TomasMartin2004/">
              <AiFillGithub />
            </a>
          </div>
          <div className="flex flex-row-reverse dark:fill-blue-500">
             <UseAnimations animation={arrowDown} size={60} />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-blue-200 rounded-full w-80 h-80 overflow-hidden md:h-85 md:w-85 dark:from-red-300">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div className=" flex flex-wrap md:flex-row">
          <div className=" lg:basis-1/2">
            <h3 className="text-4xl py-1 text-cyan-950 font-semibold dark:text-white">About me</h3>
            <p className="justify-self-center	 text-md py-2 leading-8 text-gray-800 dark:text-white">
              I am a 20-year-old systems analyst with
              solid knowledge in programming and
              software development. I am passionate
              about solving problems and continuously
              learning, improving my skills, and expanding
              my knowledge.
              </p>
              <p className="justify-self-center	 text-md py-2 leading-8 text-gray-800 dark:text-white">
              My experience with
              <span className="text-amber-400 font-bold"> react </span> y
              <span className="text-cyan-300 font-bold	"> python </span>
              has allowed me to develop web applications and  improve my skills in the field.
            </p>
          </div>
          
          <div className="overflow:hidden md:basis-1/2 lg:basis-1/2">
            <div className="overflow relative mx-auto w-100 h-100  md:h-96 md:w-96 lg:mr-4">
            <Image src={code} objectFit="cover" width={500} />
          </div>
          </div>
          </div>

        </section>
        <section>
          <div>
            <h3 className=" text-4xl py-1 text-cyan-900 font-semibold dark:text-white">Projects</h3>
          </div>
          <div className=" flex flex-col gap-10 mt-20 lg:flex-row lg:flex-wrap lg:m-10">
            <div className="basis-1/3 flex-1 mar">
              <h3 className="text-2xl py-1 text-orange-500 dark:text-white font-bold">
                Appointment Management System
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Together with an incredible team, we developed a system for a client: Sindicato de empleados de comercio de Quilmes.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                Tools: 
                <span className="text-orange-600 font-semibold">
                  {" "}
                  ReactJs, MaterialUI, Django Rest, PostgreSQL && Postman{" "}
                </span>
              </p>
              <a
                className="text-amber-600 text-xl py-2 lg:flex justify-center"
                href=""
              >
                <AiOutlineLink />
              </a>
              <Image
                src={CECQ}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <h3 className="text-2xl py-1 text-teal-950 dark:text-white font-bold">
                Gym Ecommerce
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              We created a gym e-commerce platform offering high-quality equipment, 
              activewear, and supplements.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                Tools:
                <span className="text-teal-600 font-semibold">
                  {" "}
                  ReactJs, MaterialUI, Django Rest, PostgreSQL && Postman{" "}
                </span>
              </p>
              <a
                className=" text-teal-600 text-xl py-2 lg:flex justify-center"
                href=""
              >
                <AiOutlineLink />
              </a>
              <Image
                href=""
                src={ecommerce}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            
            <div className="basis-1/3 flex-1">
              <h3 className="text-2xl py-1 text-red-600 dark:text-white font-bold ">
                Gastroenterology Center 
                
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                Front-page for a client: gastroenterology center, that allows patients to watch information about the center and the services they offer.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                Tools:
                <span className="text-red-500 font-semibold">
                  {" "}
                  NextJs, Typescript && TailwindCSS{" "}
                </span>
              </p>
              <a
                className="text-xl py-2 text-red-600 lg:flex justify-center"
                href="https://sagradocorazongastroenterologia.vercel.app/"
              >
                <AiOutlineLink />
              </a>
              <Image
                href=""
                src={clinica}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <h3 className="text-2xl py-1 text-teal-950 dark:text-white font-bold">
                Tennis Club System
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                {/* Descripcion para sistema de club de tenis en ingles */}
                We are developing a system for a tennis club that allows the management of members,
                reservations, and payments.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                Tools:
                <span className="text-cyan-500 font-semibold">
                  {" "}
                  The work has not started yet.{" "}
                </span>
              </p>
              <a
                className=" text-xl py-2 text-cyan-600 lg:flex justify-center"
              >
                <AiOutlineLink/>
              </a>
              <Image
                href=""
                src={tenis}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

          
          </div>
          <section className="px-10 py-16 bg-gray-50 dark:bg-gray-900">
            <div className="text-center">
              <h2 className="text-3xl font-bold text-teal-600 dark:text-teal-400">
                My Skills & Tools
              </h2>
              <p className="mt-4 text-gray-600 dark:text-gray-300">
                Explore the tools and technologies I use to create efficient, scalable, and visually appealing projects.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-10">
              {/* Card 1 */}
              <div className="group relative bg-teal-50 rounded-lg shadow-lg dark:bg-gray-800 transition transform hover:scale-105 hover:shadow-2xl">
                <div className="p-10 text-center">
                  <Image src={couch} width={100} height={100} alt="Tools" />
                  <h3 className="mt-6 text-lg font-semibold text-teal-600 dark:text-teal-400">
                    Tools
                  </h3>
                  <p className="mt-4 text-gray-600 dark:text-gray-300">
                    Tools that allow me to develop and overcome challenges with creativity and efficiency.
                  </p>
                </div>
                <div className="absolute inset-x-0 bottom-0 p-4 bg-teal-100 dark:bg-gray-700 opacity-0 group-hover:opacity-100 transition">
                  <h4 className="text-teal-600 font-bold dark:text-teal-400">
                    Tools I Use
                  </h4>
                  <ul className="mt-2 space-y-1 text-gray-700 dark:text-gray-300">
                    <li>React</li>
                    <li>Next.js</li>
                    <li>MySQL</li>
                    <li>PostgreSQL</li>
                    <li>Django</li>
                    <li>JavaScript</li>
                    <li>Python</li>
                    <li>C</li>
                  </ul>
                </div>
              </div>
              {/* Card 2 */}
              <div className="group relative bg-teal-50 rounded-lg shadow-lg dark:bg-gray-800 transition transform hover:scale-105 hover:shadow-2xl">
                <div className="p-10 text-center">
                  <Image src={design} width={100} height={100} alt="Add-ons" />
                  <h3 className="mt-6 text-lg font-semibold text-teal-600 dark:text-teal-400">
                    Add-ons
                  </h3>
                  <p className="mt-4 text-gray-600 dark:text-gray-300">
                    Frameworks and other tools that help me save development time.
                  </p>
                </div>
                <div className="absolute inset-x-0 bottom-0 p-4 bg-teal-100 dark:bg-gray-700 opacity-0 group-hover:opacity-100 transition">
                  <h4 className="text-teal-600 font-bold dark:text-teal-400">
                    Add-ons I Use
                  </h4>
                  <ul className="mt-2 space-y-1 text-gray-700 dark:text-gray-300">
                    <li>TailwindCSS</li>
                    <li>Sass</li>
                    <li>Material UI</li>
                    <li>Bootstrap</li>
                    <li>MongoDB</li>
                    <li>Postman</li>
                    <li>Docker</li>
                    <li>Linux</li>
                    <li>Git</li>
                  </ul>
                </div>
              </div>
              {/* Card 3 */}
              <div className="group relative bg-teal-50 rounded-lg shadow-lg dark:bg-gray-800 transition transform hover:scale-105 hover:shadow-2xl">
                <div className="p-10 text-center">
                  <Image src={design} width={100} height={100} alt="Extras" />
                  <h3 className="mt-6 text-lg font-semibold text-teal-600 dark:text-teal-400">
                    Extras
                  </h3>
                  <p className="mt-4 text-gray-600 dark:text-gray-300">
                    Other technologies and methodologies I enjoy exploring.
                  </p>
                </div>
                <div className="absolute inset-x-0 bottom-0 p-4 bg-teal-100 dark:bg-gray-700 opacity-0 group-hover:opacity-100 transition">
                  <h4 className="text-teal-600 font-bold dark:text-teal-400">
                    Extras I Explore
                  </h4>
                  <ul className="mt-2 space-y-1 text-gray-700 dark:text-gray-300">
                    <li>Agile</li>
                    <li>Scrum</li>
                    <li>Software testing</li>
                    <li>WebSockets</li>
                    <li>Unit Testing</li>
                  </ul>
                </div>
              </div>
            </div>

          </section>

        </section>
        <footer className="mt-5 flex-col text-center text-sm lg:flex lg:justify-center border-t-2 border-dashed">
          <div className='text-sky-500 p-10  footer__container dark:text-white'>
          { `Tomas Martin © ${new Date().getFullYear()}` }
          
        </div>
        
        </footer>
      </main>
    </div>
    
  );    
}
